FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY contracts/ ./contracts/
COPY scripts/ ./scripts/
COPY test/ ./test/
COPY hardhat.config.js ./
COPY wait-for-blockchain.sh ./

RUN chmod +x wait-for-blockchain.sh

EXPOSE 8545

CMD ["./wait-for-blockchain.sh"]